"""Тесты CaseEditor: сборка ``CaseDraft`` из меты и редакторов пациентов."""
from __future__ import annotations

from pathlib import Path

from PySide6.QtWidgets import QTableWidgetItem, QTabWidget
from pytestqt.qtbot import QtBot

from epicase_constructor.ui.case_editor import CaseEditor
from epicase_constructor.ui.patient_editor import PatientEditor


def test_editor_has_six_titled_tabs(qtbot: QtBot) -> None:
    """Компоновка: шесть вкладок в ожидаемом порядке внутри ``self.tabs``."""
    editor = CaseEditor()
    qtbot.addWidget(editor)

    assert isinstance(editor.tabs, QTabWidget)
    assert editor.tabs.count() == 6
    titles = [editor.tabs.tabText(i) for i in range(editor.tabs.count())]
    assert titles == [
        "Кейс и пациенты",
        "Клинический",
        "Контакты",
        "Среда",
        "СЭС",
        "Финал",
    ]


def test_add_patient_still_appends_patient_editor(qtbot: QtBot) -> None:
    """После переверстки add_patient по-прежнему кладёт ``PatientEditor`` в список."""
    editor = CaseEditor()
    qtbot.addWidget(editor)

    editor.add_patient()
    assert len(editor.patient_editors) == 1
    assert isinstance(editor.patient_editors[0], PatientEditor)


def test_empty_editor_to_draft_has_stable_autogenerated_id(qtbot: QtBot) -> None:
    """Пустой редактор → ``CaseDraft`` с автогенерированным id; id стабилен между вызовами."""
    editor = CaseEditor()
    qtbot.addWidget(editor)

    draft = editor.to_draft()
    assert draft.case_id  # непустой автогенерированный id
    assert draft.patients == ()
    # Повторный вызов даёт тот же id (стабильность в пределах сессии редактирования).
    assert editor.to_draft().case_id == draft.case_id


def test_add_and_remove_patient(qtbot: QtBot) -> None:
    """«Добавить пациента» увеличивает число редакторов, «Удалить последнего» — уменьшает."""
    editor = CaseEditor()
    qtbot.addWidget(editor)

    assert len(editor.patient_editors) == 0
    editor.add_patient_button.click()
    editor.add_patient_button.click()
    assert len(editor.patient_editors) == 2
    editor.remove_patient_button.click()
    assert len(editor.patient_editors) == 1
    # Удаление при пустом списке не падает.
    editor.remove_patient_button.click()
    editor.remove_patient_button.click()
    assert len(editor.patient_editors) == 0


def test_filled_editor_to_draft(qtbot: QtBot, tmp_path: Path) -> None:
    """Заполненные поля меты и пациента → корректный ``CaseDraft``."""
    editor = CaseEditor()
    qtbot.addWidget(editor)

    editor.title_edit.setText("Вспышка ОКИ")
    editor.author_edit.setText("Иванов")
    editor.author_rank_edit.setText("полковник")
    editor.nosology_edit.setText("Сальмонеллёз")
    editor.unit_personnel_edit.setText("150")

    editor.add_patient_button.click()
    patient = editor.patient_editors[0]
    patient.title_edit.setText("Пациент 1")
    patient.add_row_button.click()
    patient.fields_table.setItem(0, 0, QTableWidgetItem("Возраст"))
    patient.fields_table.setItem(0, 1, QTableWidgetItem("25 лет"))
    first_img = tmp_path / "img_01.png"
    first_img.write_bytes(b"A")
    second_img = tmp_path / "img_02.png"
    second_img.write_bytes(b"B")
    patient.assets_picker.add_file(str(first_img))
    patient.assets_picker.add_file(str(second_img))

    draft = editor.to_draft()
    assert draft.case_id  # непустой автогенерированный id
    assert draft.title == "Вспышка ОКИ"
    assert draft.author == "Иванов"
    assert draft.author_rank == "полковник"
    assert draft.nosology == "Сальмонеллёз"
    assert draft.unit_personnel == 150
    assert len(draft.patients) == 1
    assert draft.patients[0].fields == (("Возраст", "25 лет"),)
    assert len(draft.patients[0].assets) == 2
    assert draft.patients[0].assets[0].display_name == "img_01.png"
    assert draft.patients[0].assets[1].display_name == "img_02.png"


def test_unit_personnel_parsing(qtbot: QtBot) -> None:
    """unit_personnel: «150»→150, «»→None, «abc»→None (без падения)."""
    editor = CaseEditor()
    qtbot.addWidget(editor)

    editor.unit_personnel_edit.setText("150")
    assert editor.to_draft().unit_personnel == 150
    editor.unit_personnel_edit.setText("")
    assert editor.to_draft().unit_personnel is None
    editor.unit_personnel_edit.setText("abc")
    assert editor.to_draft().unit_personnel is None


def test_unit_personnel_invalid_formats_are_none(qtbot: QtBot) -> None:
    """Пиннинг (W5): «3.5», «1 000», «150abc» молча дают None (контракт не меняем)."""
    editor = CaseEditor()
    qtbot.addWidget(editor)

    for text in ("3.5", "1 000", "150abc"):
        editor.unit_personnel_edit.setText(text)
        assert editor.to_draft().unit_personnel is None
