"""Доменный слой. НИКАКИХ внешних зависимостей (ни PySide6, ни ORM, ни сети).

Публичный API доменной модели Case/Stage. Каждая сущность сериализуется чистыми
``to_dict``/``from_dict`` (документная модель, ADR-009).
"""
from epicase_core.domain.assets import AssetKind, AssetRef
from epicase_core.domain.attempt import (
    Attempt,
    AttemptClinical,
    AttemptContacts,
    AttemptEnvironment,
    AttemptFinal,
    AttemptMeta,
    AttemptPatients,
    AttemptSes,
    BranchResponse,
    ChoiceResponse,
    DocumentResponse,
    InspectionResponse,
    SearchLog,
    TimelineResponse,
)
from epicase_core.domain.case import Case, CaseMeta
from epicase_core.domain.documents import (
    ChoiceMatch,
    DateMatch,
    DocumentField,
    DocumentOption,
    DocumentTask,
    DocumentTemplate,
    FieldType,
    MatchRule,
    NumberMatch,
    TextMatch,
    match_rule_from_dict,
)
from epicase_core.domain.epidemiology import (
    SesLevel,
    classify_ses,
    extensive_indicator,
    intensive_indicator,
    intensive_indicator_period,
)
from epicase_core.domain.report import (
    CaseReport,
    Finding,
    FindingKind,
    StageReport,
    TimelineComparison,
    grade_case,
)
from epicase_core.domain.scheme import (
    Hotspot,
    HotspotShape,
    SchemeDocument,
    SchemeView,
)
from epicase_core.domain.search import (
    InspectionCheck,
    KeywordSearch,
    SearchEntry,
    SynonymSet,
)
from epicase_core.domain.stages import (
    BranchOption,
    BranchPoint,
    PatientCard,
    Stage,
    StageClinical,
    StageContacts,
    StageEnvironment,
    StageFinal,
    StageKind,
    StagePatients,
    StageSes,
    Timeline,
)

__all__ = [
    "AssetKind",
    "AssetRef",
    "Attempt",
    "AttemptClinical",
    "AttemptContacts",
    "AttemptEnvironment",
    "AttemptFinal",
    "AttemptMeta",
    "AttemptPatients",
    "AttemptSes",
    "BranchOption",
    "BranchPoint",
    "BranchResponse",
    "Case",
    "CaseMeta",
    "CaseReport",
    "ChoiceMatch",
    "ChoiceResponse",
    "DateMatch",
    "DocumentField",
    "DocumentOption",
    "DocumentResponse",
    "DocumentTask",
    "DocumentTemplate",
    "FieldType",
    "Finding",
    "FindingKind",
    "Hotspot",
    "HotspotShape",
    "InspectionCheck",
    "InspectionResponse",
    "KeywordSearch",
    "MatchRule",
    "NumberMatch",
    "PatientCard",
    "SchemeDocument",
    "SchemeView",
    "SearchEntry",
    "SearchLog",
    "SesLevel",
    "Stage",
    "StageClinical",
    "StageContacts",
    "StageEnvironment",
    "StageFinal",
    "StageKind",
    "StagePatients",
    "StageReport",
    "StageSes",
    "SynonymSet",
    "TextMatch",
    "Timeline",
    "TimelineComparison",
    "TimelineResponse",
    "classify_ses",
    "extensive_indicator",
    "grade_case",
    "intensive_indicator",
    "intensive_indicator_period",
    "match_rule_from_dict",
]
